#!/usr/bin/env node
/**
 * generate-tokens.js
 *
 * Reads @duxton-web/design-tokens/themes/light and generates
 * .dumi/global.less with --adm-* CSS variable overrides.
 *
 * GitLab-only — not pushed to public GitHub fork.
 * Run: node scripts/generate-tokens.js
 */

const fs = require('fs')
const path = require('path')

const tokens = require('@duxton-web/design-tokens/themes/light')

const {
  // Brand / primary
  colorBrandPrimaryDefault,
  colorBrandPrimarySoftest,

  // Status
  colorStatusPositiveDefault,
  colorStatusNoticeDefault,
  colorStatusAlertDefault,
  colorStatusNoticeAltDefault,

  // Content (text)
  colorContentDefault,
  colorContentDim,
  colorContentPlaceholder,

  // Outline (borders)
  colorOutlineSoft,
  colorOutlineDefault,

  // Background
  colorBackgroundDefault,
  colorBackgroundAlt,

  // Base neutrals
  colorBaseNeutralWhite,
  colorBaseNeutralBlack,
} = tokens

const output = `\
// AUTO-GENERATED by scripts/generate-tokens.js
// Source: @duxton-web/design-tokens/themes/light
//
// Maps --adm-* CSS variables to Grab brand (Duxton) values.
// GitLab-only — NOT pushed to public GitHub fork (origin).
//
// To regenerate: node scripts/generate-tokens.js

:root {
  // Primary brand — Grab green
  --adm-color-primary: ${colorBrandPrimaryDefault};          // colorBrandPrimaryDefault
  --adm-color-primary-light: ${colorBrandPrimarySoftest};  // colorBrandPrimarySoftest

  // Semantic status colors
  --adm-color-success: ${colorStatusPositiveDefault};          // colorStatusPositiveDefault
  --adm-color-warning: ${colorStatusNoticeDefault};          // colorStatusNoticeDefault
  --adm-color-danger: ${colorStatusAlertDefault};           // colorStatusAlertDefault

  // Accent colors (no direct Duxton equivalent — closest semantic match)
  --adm-color-yellow: ${colorStatusNoticeDefault};           // colorStatusNoticeDefault (amber)
  --adm-color-orange: ${colorStatusNoticeAltDefault};        // colorStatusNoticeAltDefault

  // Wathet (light blue tint) — replaced with brand primary softest
  --adm-color-wathet: ${colorBrandPrimarySoftest};          // colorBrandPrimarySoftest

  // Text
  --adm-color-text: ${colorContentDefault};             // colorContentDefault
  --adm-color-text-secondary: ${colorContentDim};   // colorContentDim
  --adm-color-weak: ${colorContentPlaceholder};             // colorContentPlaceholder

  // UI structural colors
  --adm-color-light: ${colorOutlineDefault};          // colorOutlineDefault
  --adm-color-border: ${colorOutlineSoft};          // colorOutlineSoft
  --adm-color-background: ${colorBackgroundDefault};      // colorBackgroundDefault
  --adm-color-box: ${colorBackgroundAlt};           // colorBackgroundAlt (fill / box background)

  // Solids
  --adm-color-white: ${colorBaseNeutralWhite};          // colorBaseNeutralWhite
  --adm-color-text-light-solid: ${colorBaseNeutralWhite}; // colorBaseNeutralWhite
  --adm-color-text-dark-solid: ${colorBaseNeutralBlack};  // colorBaseNeutralBlack
}
`

const outPath = path.resolve(__dirname, '../.dumi/global.less')
fs.writeFileSync(outPath, output, 'utf8')
console.log(`Generated: ${outPath}`)
